apiVersion: v1
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:XfzY2A/mLaAlXu/7IywPiHs4Oh8FwY/3eDywV9QYETdVC5i+uWDzSA==,iv:pE5SpP9zYv3mLvZklE5tKGTGivPYlGkIYC+Dk5G2Srs=,tag:IDfBIUvMazXXSA3Hsk+lGQ==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOS81NWRDK293MHBJRDYx
            eVJKYkhKRW5TdXVDYjUyTFZZWXZPZ3pUN1I0Cm1DQnh2NVRjcnFGb1dTTkFjbTNP
            ZWpvUm9YV2c1Z0t0OU9CbVFCS3NmWFUKLS0tIHJpSG5pWGdUMzFQZlduQ2FBTFNB
            TTRxUWhJY1ZmZlYwbnZBRE52U3R4MHMKSa5vFCiczIS8phTLEzI+4BuQUcKM5B/L
            Ws2YeVAncXGY14+q7xTIhiftHcwJEEwi+YQnFYmA7UcEV5MoGSkaGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T11:22:15Z"
    mac: ENC[AES256_GCM,data:cNMpzVF+n9Lmy/xnxICvzv9tU5KnPlM8HP0lcOhiXBjxa0pA6NCNgvQl/3JExAuE8XtrsqS1DkS7sgrQofi6sXvEG4asDm1Ld/g6n8bNPFlUSDjVeVTsRs4oIw/w2XlN12RbefnlxPUefK0ncn7PGVLyk7t8yHtlTU5hDoWULFE=,iv:aTMYYbf+tV5Es1fel03xgCDx8fD1WjktEgAQdYJqjCc=,tag:yeV6slTxYZQTyP99EDUpHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0