apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sops-store
spec:
  provider:
    kubernetes:
      remoteNamespace: flux-system
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: flux-system
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
