apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - repository.yaml
  - secret.yaml
  - release.yaml
  #- grafana-tailscale-ingress.yaml
configMapGenerator:
  - name: general-values
    files:
      - ./values/general.yaml
secretGenerator:
  - name: contactpoints-values
    files:
      - ./values/contactpoints.yaml
generatorOptions:
  disableNameSuffixHash: true
