apiVersion: v1
stringData:
    admin-user: ENC[AES256_GCM,data:eb0PYIk=,iv:jx1DbzRN6kPDvk0In/2skTDJ4Cmjc2XEx+XKyC30j/Y=,tag:wiDJMm0+R6pdju8oXE3/mA==,type:str]
    admin-password: ENC[AES256_GCM,data:jCUpV6uAPg==,iv:h/aOS9GXmSEtdQ+A6xWzyeglpQEJIHFpzcb7p8BFcj4=,tag:UltTAK7Hcn4ZrMsglX0T1Q==,type:str]
kind: Secret
metadata:
    name: grafana-admin-creds
sops:
    age:
        - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRko4SFBJV2JFTEd2aFZF
            UFl0aWlJWDB4UnVUZ1Q5YUR0T0tMaXpYeGhZCkpFNENzME8waXBBWk5FRFR1eVND
            V1RkOXB0a3BxWkg4bVlCa2VXU2tFLzgKLS0tIGRmLzJBZFhJbkdzSVgxditJZkhV
            YjkrY2ROTi9OejEvV0UrV2ZtMzcyMTAKlka4AOZ6AH1rgETXv472BRnDPxb0zmuH
            YNoFimICtSphliMZCtxJ03u7qy9EeYUeF/tatEby9s+vUzju4H/MRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T13:50:57Z"
    mac: ENC[AES256_GCM,data:MAMgkEO3X9i5CfYJTpeq2kyoVh5PWxfjFMaKtwtN5UV3R+cATwwQZ79k1+tECbT6VmYdnbB0oCvhGVRLxVcmN0N0NL5oCAf1vuFGPQEooZ5+2kkLG5NWESK/jOXZ45hAUNm1JiVPfZVW1SKHLh5dEAfSA2haaHG4CKxceVl4cPs=,iv:EMQmioZBGNEYQiNcYcugiYvPfOtgWlHnQqT2fn0W7MI=,tag:/GUGcjdLfg5Luf6HZLbGrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
