apiVersion: v1
data:
  admin-user: ENC[AES256_GCM,data:/sRHAyY=,iv:HUxX8qhW58dvTxuFEr9tWa4s0uM9uynUdZzMPQESJYQ=,tag:0xJ4B7ctadFVbVEGQSpKYw==,type:str]
  admin-password: ENC[AES256_GCM,data:cgQ904lHsA==,iv:3XVMddFyRRFc621h1m66qaOwtEL9GnVORULYyGQWB3U=,tag:gcJzdUvR/FOiJJxa53HdCw==,type:str]
kind: Secret
metadata:
    name: grafana-admin-creds
sops:
  age:
    - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RUk4b2RFYW0vQnVyTXJm
        cFp1SmxJT1JwMmcyZWVla3pVSmNJRXU3SVFZCmN0bXNEMW16MXlnSFFLN2dad0lU
        bWNPcUxxUmMxWE9nZXV2Z1JvVTZSL28KLS0tIEs4Q3NRcEZNS2dvRnJta3dJRS8x
        UVhKZU9NTDFPK3I5UU9tTGgxSUk4OFUKzfQbWeHqt1wRhuM2iiU9CF1LmZR8eOb7
        /h7sr11s1F9SXQ2D60P1D2QhuuIjEjg9DN6+yl83ZcGb8XBxBeNStA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T13:47:53Z"
  mac: ENC[AES256_GCM,data:4aGYo5ttZk68ZDLtEU5mkJjEuZ2KkXE/NuA4SNJPwq3W1eG1ohS61aQZXEBsCDDkbJu6Ec5zIMb9/VKzwVzXpQdMcPd91l/qNVi7jpVtfgtmhcZqOU6MZvz4Doue6evEIZXuqZVvl5mnnIoo2aH3BlqzEx32Q1EFFjyTgaTEMzU=,iv:0GXvhzFwxi0oJ4AxXLiYdMxAO7UAGhPRdVkIIzpWzk4=,tag:5rNuxbyc8sLqofJOa7GnQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0