apiVersion: v1
data:
  admin-user: ENC[AES256_GCM,data:FyBcNVc=,iv:DdSzYN//3IqCPGTfHphL9amTABEa22+IEKDpgn2pxxs=,tag:3XdWadVb4P7CQQYTBcycRw==,type:str]
  admin-password: ENC[AES256_GCM,data:rMi1QHp4Vw==,iv:KuVSFElAurZuuZC8vNCRCqDMpr4xQBux3uGqvaMpjy0=,tag:nRpXR+YYG5CdDfEh4lJlyg==,type:str]
kind: Secret
metadata:
    name: grafana-admin-creds
sops:
  age:
    - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdVlDWnhHZlhpbnJpT0xL
        R1JwUmJJbFMzT1VLN3BlK05Jd0ZhOGdMSHdnCnBlcFFIemJwa3dnelQ5YWdTa3V5
        L2JGLzlxNzBjalg4QWhGYjU2Uzd2ajAKLS0tIDY1UDhZQm9rYzBGcjhuWDgxME1N
        Ti9tZmdxNTBSUjdYR3JGempNSStzZzAK8+6cAREAEhaPOuxaKYDGnsBCQ1Aqc08k
        gEXwm0RBwMosqa2oaNASgr7BoV5UNzJ6EeNHKUNWv4RNVhkpkw8oCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T13:38:54Z"
  mac: ENC[AES256_GCM,data:sNZZQKGTXdRhHvjR/C/9CEUPwDGwT/RKxM0zV2/EtScmUcNhOM8nIY6hPtOKzeLwtOFPuvi3mwigCjVWNGO4pDP4B/uYKmMqNVH1og4uudGNHXdb91T+qvietMtJoKhtFB65PpepRIHSK3nFxnEn9CrpADBZd1dGZHBbAnyLBqQ=,iv:Fhu1N+2WYOACmrNmgBug6pEjr6eZEYQ8ym6YfPWx1is=,tag:VmwC6mWXSSMFZpmU+fciAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0