apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: netbird-operator
    namespace: netbird 
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: kubernetes-operator
            sourceRef:
                kind: HelmRepository
                name: netbird-helmrepo 
    values:
      managementURL: "https://netbird.gionsihome.duckdns.org:443"
      cluster:
        name: pi3s
      ingress:
        enabled: true
        router:
          enabled: true
      netbirdAPI:
        keyFromSecret: 
          name: "netbird-mgmt-api-key"
          key: "NB_API_KEY"