apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: netbird 
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: kubernetes-operator
      sourceRef:
        kind: HelmRepository
        name: netbird-helmrepo 
  valuesFrom:
    - kind: Secret
      name: values
      valuesKey: values.yaml
