apiVersion: v1
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:xCicMWxMM84atycVGotNmaB4DQ4zKgyXditnX3vFJ8MvX+GME577Hg==,iv:JbDLHCfl+UAKyJZeQB/D3duLN4zihjy9rX6VaFCY8G8=,tag:oJcI02eo3EB7Txe1YafJyg==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bXhFTHN6bVkrQTRLblBS
            dFFCeDhHKzU5emF5QjltbnZ2U0cvOUhJNXpJCjBmMkNORVNnaEpWR3plV2JEeHg1
            MnpMSkkxM2hlWFoxa3l2Zm5HNklzNVEKLS0tIGRHSmVrYTBzczNETGZTL0JiTXdx
            QTBROWhEQXcyL1R6T09vYzhNTWU0RXMKUtuUTzvad+kPiMpTzwhngC5RXzuqSC8/
            NRvdTlNitd8/3jPpDKoCRQ8zwDCZ4KsNaEmC9JeRtq/brGhBoUdPjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T10:04:46Z"
    mac: ENC[AES256_GCM,data:e9cNspuQGTplMJXjMsZ/n5xrLmhw3sjzV+ealaPnIyMjnV3sdlDFD8UI4yBy7EN4ydyEhsGajvXa1gKVo4GHFnZ1V5CKxpbi8u3W23YaF3WmHSTqFud4IeE/IyXwpS1VMacHc9sxofMIdYtZzgfWDeVsUIIrvS0vmypBVO6aMCI=,iv:zeGkz0f+Txq8l6P0x3wH2d50hlixEaqt5Hxk032y18I=,tag:8KHey/81oWOYIwTkq54XnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
