apiVersion: v1
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:CqNsyLFwpJ4qA8GtuAuUOSdJ1Rou0DuFGLbnWDvqMZIofma8vZV/bA==,iv:RTVqArZFrsNvmerUZ9N5EeJB1QHYue6N+dPXv0cwRhA=,tag:8XB9cmfMLcI4g+thAcQdWQ==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeENmOUxLTlVVY1ZKT2ZQ
            ZUhrZ2l5aDNmUG5tRFg1TksrbEpJVkc2MFEwCkdXVHJrL0ZSVkUxYVhUanJSTlNI
            SGRMSTZmOXFWUXRJRG14eHMvR1VQT0UKLS0tIEVOT252TkwreHlTV2N6WnNwdlU0
            bXVLdUpjcU5OOGVJZDFpcmpxYUFHN2sKVl8d4m4PyCf5g6Dh2XvZ4LU+ovp3MQWy
            3NWzPjUpU/GRKFSfsPe0fUwfguWYwyRWbu1rdotweopJ7q/SrQY9DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T13:41:31Z"
    mac: ENC[AES256_GCM,data:1c5fPR93cpSzIhhTxZQMQwIiMI0CaSwzYcJR7UxMjBb3oXEqhuO5Y/ss0XwfVlbqTqGl5tMHM/4NsFMAARYimgMlO3JdsHPiFatrzm8iYTju2r3hKTx7D2nPJx4V7ugOhQtxvI/f1s/V+mNEdCi4q16QhvlQeafJfdNiYe+CvUU=,iv:aEVrMjPLyLm2mQxYflQxw+IEjuuZVt80vfml6cVxi0c=,tag:rPQrzryofVEMOzJi8tYnow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
