apiVersion: v1
kind: ConfigMap 
metadata:
  name: hass-config
data:
  configuration.yaml: |
    # Load default config
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes
    
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    # Reverse proxy config
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.1.0/24
        - 10.42.0.0/24
        - 127.0.0.1
        - ::1